"""add_music_schools_and_archive

Revision ID: 7fca4f9e1636
Revises: f66da63091ae
Create Date: 2026-05-20 19:27:50.604970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fca4f9e1636'
down_revision: Union[str, None] = 'f66da63091ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_schools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('music_school_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_full_name', sa.String(length=255), nullable=False),
    sa.Column('music_school_id', sa.String(length=36), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('diploma_serial', sa.String(length=50), nullable=False),
    sa.Column('diploma_number', sa.String(length=50), nullable=False),
    sa.Column('given_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('ocr_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('ocr_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['music_school_id'], ['music_schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('search_index_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_type', sa.String(length=50), server_default='general', nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_school_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_users_music_school_id', 'music_schools', ['music_school_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_music_school_id', type_='foreignkey')
        batch_op.drop_column('music_school_id')

    with op.batch_alter_table('search_index_jobs', schema=None) as batch_op:
        batch_op.drop_column('entity_type')

    op.drop_table('music_school_documents')
    op.drop_table('music_schools')
    # ### end Alembic commands ###
